[project]
name = "mcp-cicilan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.8.0",
]

[project.scripts]
mcp-cicilan = "mcp_cicilan.mcp_cicilan:main"